# Generated by Django 5.2 on 2026-07-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_label', models.CharField(max_length=50, verbose_name='課程標籤')),
                ('lesson_count', models.FloatField(verbose_name='堂數')),
                ('question_count', models.FloatField(verbose_name='解題數量')),
                ('preparation_fee', models.FloatField(verbose_name='準備費')),
                ('image_fee', models.FloatField(verbose_name='形象費')),
                ('material_fee', models.FloatField(verbose_name='教材加給')),
                ('duration_fee', models.FloatField(verbose_name='授課基礎費')),
                ('question_fee', models.FloatField(verbose_name='解題費用')),
                ('total_salary', models.FloatField(verbose_name='總薪資')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='紀錄時間')),
            ],
            options={
                'verbose_name': '薪資紀錄',
                'verbose_name_plural': '薪資紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
